server:
  port: 9003

spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true 
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health, refresh"
  endpoint:
    health:
      show-details: always