server:
  port: 8001 
  #servlet:
  #  context-path: /api

spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gestion_customer_db
    username: lorince
    password: lorince
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc: 
          time_zone: UTC 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client: 
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health, refresh"
  endpoint:
    health:
      show-details: always